FROM eclipse-temurin:17-jre

ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US:en' \
    LC_ALL='en_US.UTF-8'

ARG SONARQUBE_VERSION=9.8.0.63668
#ARG SONARQUBE_ZIP=/opt/sonarqube-${SONARQUBE_VERSION}
ARG SONARQUBE_ZIP=/opt/ansible/ansible-sonarqube-pg-nginx/binary/sonarqube/sonarqube-${SONARQUBE_VERSION}.zip
ARG SONARQUBE_BIN=/opt/ansible/ansible-sonarqube-pg-nginx/binary/sonarqube/
ENV JAVA_HOME='/opt/java/openjdk' \
    SONARQUBE_HOME=/opt/sonarqube \
    SONAR_VERSION="${SONARQUBE_VERSION}" \
    SQ_DATA_DIR="/opt/sonarqube/data" \
    SQ_EXTENSIONS_DIR="/opt/sonarqube/extensions" \
    SQ_LOGS_DIR="/opt/sonarqube/logs" \
    SQ_TEMP_DIR="/opt/sonarqube/temp"

#VOLUME ${SONARQUBE_BIN}:/opt

COPY ./sonarqube/sonarqube-${SONARQUBE_VERSION}.zip /opt

RUN set -eux; \
    adduser --system --uid 1000 sonarqube; \
    addgroup --system --gid 1000 sonarqube; \
    adduser sonarqube sonarqube; \
    apt-get update; \
    apt-get install -y gnupg unzip curl bash fonts-dejavu; \
    echo "networkaddress.cache.ttl=5" >> "${JAVA_HOME}/conf/security/java.security"; \
    sed --in-place --expression="s?securerandom.source=file:/dev/random?securerandom.source=file:/dev/urandom?g" "${JAVA_HOME}/conf/security/java.security"; \
#    for server in $(shuf -e hkps://keys.openpgp.org \
#                            hkps://keyserver.ubuntu.com) ; do \
#        gpg --batch --keyserver "${server}" --recv-keys 679F1EE92B19609DE816FDE81DB198F93525EC1A && break || : ; \
#    done; \
#    mkdir --parents /opt; \
#    cd /opt; \
#    curl --fail --location --output sonarqube.zip --silent --show-error "${SONARQUBE_ZIP}"; \
#    curl --fail --location --output sonarqube.zip.asc --silent --show-error "${SONARQUBE_ZIP}.asc"; \
#    cp ${SONARQUBE_ZIP} /opt; \
#    cp ${SONARQUBE_ZIP}.asc /opt; \
#    gpg --batch --verify sonarqube-${SONARQUBE_VERSION}.zip.asc sonarqube-${SONARQUBE_VERSION}.zip; \
    chown -R sonarqube:sonarqube /opt; \
    unzip -q /opt/sonarqube-${SONARQUBE_VERSION}.zip; \
    mv "sonarqube-${SONARQUBE_VERSION}" sonarqube; \
#    rm sonarqube-${SONARQUBE_VERSION}.zip; \
    rm -rf ${SONARQUBE_HOME}/bin/*; \
    ln -s ${SONARQUBE_HOME}/lib/sonar-application-${SONARQUBE_VERSION}.jar ${SONARQUBE_HOME}/lib/sonarqube.jar; \
    chmod -R 555 ${SONARQUBE_HOME}; \
    chmod -R ugo+wrX "${SQ_DATA_DIR}" "${SQ_EXTENSIONS_DIR}" "${SQ_LOGS_DIR}" "${SQ_TEMP_DIR}"; \
    apt-get remove -y gnupg unzip curl;

WORKDIR ${SONARQUBE_HOME}
EXPOSE 9000

USER sonarqube
STOPSIGNAL SIGINT

ENTRYPOINT ["/opt/java/openjdk/bin/java","-jar","lib/sonarqube.jar","-Dsonar.log.console=true"]
